{{- if .Values.enabled }}
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: mcoa-instance
  namespace: openshift-logging
  labels:
    app: {{ template "logginghelm.name" . }}
    chart: {{ template "logginghelm.chart" . }}
    release: {{ .Release.Name }}
spec:
{{- fromJson .Values.clfSpec | toYaml | nindent 2 }}
{{- end }}