{{- if .Values.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-opentelemetry-operator
  labels:
    app: {{ template "tracinghelm.name" . }}
    chart: {{ template "tracinghelm.chart" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: mcoa-opentelemetry
  labels:
    app: {{ template "tracinghelm.name" . }}
    chart: {{ template "tracinghelm.chart" . }}
    release: {{ .Release.Name }}
{{- end }}
